version: '3'
services:
  wordpress:
    image: wordpress:php8.2-fpm
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepassword
      WORDPRESS_DB_NAME: exampledb
      TZ: Asia/Taipei  # 在這裡定義時區
    volumes:
      - ./wordpress:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf        
    networks:
      - WordPress_network
    restart: always

  database:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
      TZ: Asia/Taipei  # 在這裡定義時區
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - WordPress_network
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx/log/:/var/log/nginx/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  # 只映射到主機的80端口
    networks:
      - WordPress_network
    restart: always
    environment:
      TZ: Asia/Taipei

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # 如果需要从主机访问 Redis，请映射端口
    networks:
      - WordPress_network
    restart: always
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf  # 映射本地配置文件到容器中
    command: redis-server /usr/local/etc/redis/redis.conf  # 使用自定义配置文件启动 Redis


networks:
  WordPress_network:
    driver: bridge
