version: '3'
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepassword
      WORDPRESS_DB_NAME: exampledb
      TZ: Asia/Taipei  # 在這裡定義時區
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - WordPress_network
    restart: always

  database:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
      TZ: Asia/Taipei  # 在這裡定義時區
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - WordPress_network
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log/:/var/log/nginx/
    ports:
      - "80:80"  # 只映射到主機的80端口
    networks:
      - WordPress_network
    restart: always
    environment:
      TZ: Asia/Taipei

networks:
  WordPress_network:
    driver: bridge
